counter caracter
titosilva/LinkCodeSim pull request #18
Opened 2022-04-08 13:39 UTC by joaopedro711

2022-04-09 20:47 UTC, titosilva requested changes

2022-04-09 20:47 UTC, titosilva commented on src/Simulador.cpp
> +#include "CamadaEnlace.cpp"
Essa linha causa um erro de compilação com o comando "make". Como o professor irá compilar usando esse comando, acho melhor retirar.

É uma boa prática dar includes somente em arquivos de header (.hpp). Os arquivos .cpp devem ser adicionados ao comando de compilação.

2022-04-09 20:47 UTC, titosilva commented on src/CamadaEnlace.cpp
> +    for(int i=(quadro.size()-1); i>7; i--){
Acredito que o professor irá querer "sacanear" o nosso código. Ele irá tentar inserir um byte a mais no quadro, e a contagem de bytes não deve simplesmente ler esse quadro. O natural (apesar de não ser o melhor) seria que quadros inseridos seriam ignorados. 

Por exemplo, imagine que o quadro possui 8 bytes mais o byte de contagem (9 bytes no total). Nesse caso, se o professor inserir mais um byte no quadro com o objetivo de testar o nosso código, o quadro passará a ter 10 bytes no total, mas a contagem não será mudada. Na vida real, fora do nosso código, quando o quadro fosse recebido, seria lido que o quadro é composto por 9 bytes, e assim, mesmo que na verdade tenha 10 bytes, só seriam lidos 9 bytes. O byte inserido pelo professor deveria ser ignorado. Dessa forma, acredito que a forma correta de implementar essa função não é ignorar os primeiros 8 bits, mas lê-los e utilizá-los corretamente.

2022-04-10 15:18 UTC, joaopedro711 commented on src/Simulador.cpp
> +#include "CamadaEnlace.cpp"
blz, vou retirar.

2022-04-10 15:21 UTC, joaopedro711 commented on src/CamadaEnlace.cpp
> +    for(int i=(quadro.size()-1); i>7; i--){
Não entendi. Esse código funciona assim. Insere uma palavra de 3 bytes, "TR1", o código irá contar quantos bytes tem a palavra e irá inserir esse valor na frente do quadro (quantidade de bytes + palavra). No fim do processo basta retirar essa quantidade de bytes do quadro. 
Não conta o byte de contagem, ele é inserido depois de contar os bytes e retirado no fim do processo.

2022-04-13 11:54 UTC, titosilva commented on src/CamadaEnlace.cpp
> +    for(int i=(quadro.size()-1); i>7; i--){
Optado por manter o código como está

2022-04-14 21:57 UTC, closed without merging